### ISSUE TITLE
Add note or warning explaining scope differences in ES6 arrow functions vs normal functions.

### ISSUE THREAD

**Issue by adilasif** [learn-co-curriculum/js-object-oriented-this-walkthrough-readme#2]
Normal functions in JavaScript bind their own `this`, but ES6 arrow functions do not.

Here is an an example:

```
function Obj() {
  this.string = 'I am in the inner scope';
}

Obj.prototype.arrowFun = () => console.log(this.string);
// uses the "this" keyword to call the object's "string" property to the console

Obj.prototype.normalFun = function() {
  console.log(this.string);
};
// also uses the "this" keyword to print the object's "string" property to the console

const testObj = new Obj();

testObj.arrowFun(); // the "this" keyword will return "undefined":

> undefined

testObj.normalFun(); // the "this" keyword will return the expected result:

> I am in the inner scope
```

As a side note, for this reason, arrow functions are best reserved for non-method functions.

**Comment by cjbrock** [comment]
Thanks for reporting this issue. We're now aware of it and are tracking it [here](https://github.com/learn-co-curriculum/js-object-oriented-this-walkthrough-readme/issues/4).  We will add this to our internal work queue and
notify you when it is resolved.

We're closing this issue but invite you to follow progress at that URL.

//<3 Corinna
