### ISSUE TITLE
Final statement in arrow function section is WRONG/TYPOS? 

### ISSUE THREAD

**Issue by AubreyNeimeier** [learn-co-curriculum/js-object-oriented-this-walkthrough-readme#5]
"The arrow function inside greeting uses this from the class method, which refers to the person object."

This statement in the arrow function section doesn't seem right. We haven't gotten to class methods yet and there is no 'greeting' defined in the example. Only 'greet'.  

If you read this example carefully, that statement doesn't make any sense.

**Comment by maxwellbenton** [comment]
Hi @AubreyNeimeier,

Thank you for spotting this and bringing it to our attention. You're absolutely correct that that sentence did not make any sense. We've updated that section and the following for clarity and believe this issue has been resolved.

Thank you for contributing to a learn.co lesson!
